(() => {
 'use strict';
 const products=window.KRON_PRODUCTS,groups=window.KRON_SERIES;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const href=r=>'?sku='+encodeURIComponent(r.model);
 const money=()=>window.KRON_PRICE.confirmed?'¥ '+window.KRON_PRICE.amount.toLocaleString('zh-CN'):'价格待确认';
 const photo=(r,lazy=true)=>'<span class="kron-photo" data-model="'+r.model+'"><img src="'+r.image+'" alt="'+esc(r.name+'，'+r.strap)+'" '+(lazy?'loading="lazy"':'fetchpriority="high"')+'></span>';
 const card=r=>'<a class="product-card kron-card" href="'+href(r)+'"><div class="product-photo">'+photo(r)+'<span class="card-ref">'+r.model+'</span><span class="card-open" aria-hidden="true">↗</span></div><div class="card-info"><span class="overline">KRONSEGLER / '+r.series+'</span><h3>'+esc(r.color)+' · '+esc(r.strap)+'</h3><span class="card-color"><i style="--swatch:'+r.swatch+'"></i>'+esc(r.model)+'</span><p>'+money()+(window.KRON_PRICE.confirmed?'<small>'+window.KRON_PRICE.label+'</small>':'')+'</p></div></a>';
 const archive='<img src="assets/kronsegler/brand-archive.jpg" alt="KronSegler 品牌资料中的腕表视觉" width="750" height="1235" fetchpriority="high">';
 const brandLink='?brand=kronsegler';
 function activate(){document.body.classList.add('kron-page');document.querySelectorAll('a[href="?brand=kronsegler"]').forEach(a=>a.setAttribute('aria-current','page'));}
 function home(main,params){
  activate();document.title='KRONSEGLER 康斯格 · 腕表系列 · 时计';
  main.innerHTML='<div class="kron-brandbar wrap"><a href="./">时计腕表</a><span>/</span><span>KRONSEGLER 康斯格</span><a href="./#collection">返回原有腕表系列 ↗</a></div>'+
   '<section class="kron-hero"><div class="kron-hero-copy"><span class="overline">THE KRONSEGLER COLLECTION</span><p class="kron-wordmark">KronSegler<span>康 斯 格</span></p><h1>把故事，<br>留在时间里。</h1><p class="kron-intro">从盘面的精巧层次，到腕间的从容表达。<br>探索康斯格 745、746 与 779 系列。</p><a class="button light" href="#kron-collection">探索 15 款腕表 <span>↓</span></a></div><figure class="kron-archive">'+archive+'<figcaption>KRONSEGLER · 品牌资料视觉 / 2023</figcaption></figure></section>'+
   '<nav class="kron-tabs" aria-label="康斯格系列"><a href="#kron-collection" data-kron-series="all">全部款式 <sup>15</sup></a>'+Object.keys(groups).map(k=>'<a href="#kron-collection" data-kron-series="'+k+'">'+k+' 系列 <sup>05</sup></a>').join('')+'<a href="#kron-story">品牌故事</a></nav>'+
   '<section class="wrap kron-catalog" id="kron-collection"><div class="section-title"><div><span class="overline">THREE COLLECTIONS. INDIVIDUAL EXPRESSION.</span><h2>三种表达，各有章法。</h2></div><p>选择系列，找到你的腕间风格。</p></div><div class="kron-tools"><label>腕表系列<select id="kron-series"><option value="all">全部系列</option>'+Object.keys(groups).map(k=>'<option value="'+k+'">'+k+' 系列</option>').join('')+'</select></label><label>颜色<select id="kron-color"><option value="all">全部颜色</option>'+[...new Set(products.map(r=>r.color))].map(c=>'<option>'+c+'</option>').join('')+'</select></label><label class="kron-model-search">搜索型号<input id="kron-model" type="search" placeholder="例如 KS745.21.01.32.21"></label><button class="text-link" id="kron-reset">重置</button><span id="kron-count" role="status">15 款腕表</span></div><div class="kron-collection-caption" id="kron-caption"></div><div class="product-grid" id="kron-grid">'+products.map(card).join('')+'</div></section>'+
   '<section class="kron-story" id="kron-story"><div><span class="overline">A STORY IN EVERY DETAIL</span><h2>不只记录时间，<br>也承载灵感。</h2></div><div><p>康斯格的品牌资料将历史、天文与哲学列为腕表设计的灵感来源。对时间的理解，也融入盘面布局、色彩与细节之中。</p><p>在这里，分别探索 745、746、779 三个系列。每一款都拥有独立的型号与商品资料页，便于选款、分享与核对。</p><small>品牌理念摘述自销售方提供的《KronSegler康斯格品牌介绍2023》。本站为销售方商品展示专区，不代表品牌官方认证。</small></div></section>'+
   '<section class="service-band wrap"><div><span class="overline">PRODUCT INFORMATION</span><h2>每一款，都有资料可查。</h2><p>查看型号、配色与规格；本批供应数量不等同于全球发行限量。</p></div><a class="button outline" href="?page=lookup">按型号查询 <span>↗</span></a></section>';
  const s=document.querySelector('#kron-series'),c=document.querySelector('#kron-color'),q=document.querySelector('#kron-model');
  function update(){const list=products.filter(r=>(s.value==='all'||r.series===s.value)&&(c.value==='all'||r.color===c.value)&&r.model.toLowerCase().includes(q.value.trim().toLowerCase()));document.querySelector('#kron-grid').innerHTML=list.length?list.map(card).join(''):'<p class="no-results">没有符合条件的款式。请减少筛选条件，或点击“重置”。</p>';document.querySelector('#kron-count').textContent=list.length+' 款腕表';const g=groups[s.value];document.querySelector('#kron-caption').innerHTML=g?'<span class="overline">COLLECTION '+s.value+'</span><h3>'+g.theme+'</h3><p>'+g.copy+'</p>':'';document.querySelectorAll('[data-kron-series]').forEach(a=>{if(a.dataset.kronSeries===s.value)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});}
  s.onchange=c.onchange=q.oninput=update;document.querySelector('#kron-reset').onclick=()=>{s.value=c.value='all';q.value='';update();};
  document.querySelectorAll('[data-kron-series]').forEach(a=>a.onclick=()=>{s.value=a.dataset.kronSeries;c.value='all';q.value='';update();});
  if(groups[params.get('series')])s.value=params.get('series');update();
 }
 function product(main,r){
  activate();document.title=r.model+' · 康斯格 '+r.series+' 系列 · 时计';
  main.innerHTML='<div class="breadcrumbs wrap"><a href="./">首页</a><span>/</span><a href="'+brandLink+'">康斯格</a><span>/</span><span>'+r.model+'</span></div><article class="detail wrap kron-detail"><div class="detail-gallery"><div class="kron-product-stage">'+photo(r,false)+'<span class="overline">KRONSEGLER / '+r.series+'</span></div><p>销售方商品资料图 · 当前为资料表缩略图，细节请核对实物</p></div><div class="detail-info"><span class="overline">KRONSEGLER · COLLECTION '+r.series+'</span><h1>康斯格 '+r.series+' 系列</h1><p class="detail-color">'+r.color+' · '+r.strap+'</p><p class="reference">REF. '+r.model+'</p><div class="detail-price">'+money()+'<span>'+(window.KRON_PRICE.confirmed?window.KRON_PRICE.label+' · CNY':'公开售价正在核对，请联系销售方确认')+'</span></div><p class="product-description">'+groups[r.series].copy+'</p><div class="variant-label">选择款式 <span>'+r.color+' / '+r.strap+'</span></div><div class="kron-variants">'+products.filter(x=>x.series===r.series).map(x=>'<a href="'+href(x)+'" aria-label="'+esc(x.color+' '+x.strap+' '+x.model)+'" '+(x===r?'aria-current="true"':'')+'>'+photo(x)+'<small>'+x.color+'</small></a>').join('')+'</div><button class="button dark full" id="kron-share">复制此款链接 <span>↗</span></button><p class="kron-share-status" id="kron-share-status" role="status"></p><div class="detail-facts"><details open><summary>商品信息 <span>+</span></summary><dl>'+[['品牌','KRONSEGLER 康斯格'],['商品型号',r.model],['系列',r.series+' 系列'],['颜色',r.color],['表盘尺寸',r.diameter],['防水标示',r.waterResistance],['机芯',r.movement],['本批供应',r.supply+' 枚']].map(([k,v])=>'<div><dt>'+k+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl></details><details><summary>价格与资料说明 <span>+</span></summary><p>型号、配色、规格与供应数量来自销售方提供的企业渠道资料，录入日期 '+r.dataAsOf+'。本批供应量不是已核实的全球限量。</p><p>'+(window.KRON_PRICE.confirmed?'人民币公示价由销售方确认，具体成交价格、税费及库存以订单为准。':'资料表价格栏标注“欧洲官方价／汇率变动”，币种及公开价格口径尚待销售方确认，暂不对外标注官方人民币价格。')+'</p><p>机芯、防水及售后以实物随附说明与购买凭证为准。康斯格专区尚未签发单表二维码，不将款式链接作为实物唯一身份或鉴定凭证。</p></details></div><a class="text-link" href="?page=service">资料与售后 ↗</a></div></article><section class="related wrap"><div class="section-title"><div><span class="overline">IN THE SAME COLLECTION</span><h2>同系列，更多选择</h2></div><a class="text-link" href="'+brandLink+'&series='+r.series+'#kron-collection">查看 '+r.series+' 系列 ↗</a></div><div class="product-grid">'+products.filter(x=>x.series===r.series&&x!==r).map(card).join('')+'</div></section>';
  document.querySelector('#kron-share').onclick=async()=>{const url=new URL(href(r),location.href).href,out=document.querySelector('#kron-share-status');try{await navigator.clipboard.writeText(url);out.textContent='款式链接已复制';}catch{out.textContent='请复制浏览器地址栏中的完整链接。';}};
 }
 function teaser(){return '<section class="kron-teaser wrap"><div><span class="overline">NEW COLLECTION / KRONSEGLER</span><h2>康斯格，<br>另一种时间表达。</h2><p>745 · 746 · 779<br>三个系列，十五款腕间风格。</p><a class="button dark" href="'+brandLink+'">探索康斯格 <span>↗</span></a></div><a class="kron-teaser-art" href="'+brandLink+'" aria-label="探索康斯格腕表">'+archive+'</a></section>';}
 function search(q){return products.filter(r=>(r.model+' '+r.name+' '+r.strap+' KRONSEGLER').toLowerCase().includes(q)).map(r=>'<a class="search-result" href="'+href(r)+'">'+photo(r)+'<span>'+esc(r.name)+'<small>'+r.model+'</small></span><strong>'+money()+'</strong></a>').join('');}
 function lookup(r){return '<div class="lookup-match kron-lookup">'+photo(r)+'<div><span class="overline">康斯格 · 款式资料</span><h2>'+esc(r.name)+'</h2><p>'+r.model+'</p><strong>'+money()+'</strong><a class="text-link" href="'+href(r)+'">查看完整资料 ↗</a></div></div>';}
 window.KronCollection={home,product,teaser,search,lookup};
})();
